### ISSUE TITLE
User authentication required to logout of the app

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect-universal-android#26]
There have been several incidents of Rangers logging out of the app inadvertently in the field and not being able to log back in. This has reduced confidence in use of the app.  

Recommended remediation is to require password authentication in order to be able to log out of the app., together with an explanatory message about what will happen if logout is successful.  

This should prevent inadvertent logout from occurring.

**Comment by sbearcsiro** [comment]
Requiring a password to logout requires storing the password on the device to allow for a logout when offline, which is not good security practice.  An alternative is to bury the logout option in a settings menu.  This should prevent any accidental logouts as it requires 4 touches to achieve a logout (1. open drawer menu 2. click settings button in menu 3. click logout in settings 4. click confirm on the dialog).

**Comment by pbrenton** [comment]
Thanks Simon, that sounds like a reasonable solution.
P
